name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      plugins: ${{ steps.matrix.outputs.plugins }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: matrix
        run: |
          make ci-matrix >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        plugin: ${{ fromJSON(needs.matrix.outputs.plugins) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build plugin
        run: make ${{ matrix.plugin }}
